name: Build client
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, arch: x64 }
          - { os: ubuntu-latest, arch: arm64 }
          - { os: macos-latest, arch: x64 }
          - { os: macos-latest, arch: arm64 }
          - { os: macos-latest, arch: universal }
          - { os: windows-latest, arch: x64 }
          - { os: windows-latest, arch: arm64 }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - run: pnpm make --arch ${{ matrix.arch }}
      - uses: actions/upload-artifact@v3
        with:
          name: client-${{ matrix.os }}-${{ matrix.arch }}
          path: out/make
